# Generated by Django 2.2.13 on 2020-06-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magicauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magictoken',
            old_name='key',
            new_name='old_key',
        ),
    ]
