# Generated by Django 2.2.13 on 2020-06-25 13:57

from django.db import migrations, models
import django_cryptography.fields
import magicauth.utils


class Migration(migrations.Migration):

    dependencies = [
        ('magicauth', '0002_rename_old_key_before_adding_encrypted_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='magictoken',
            name='key',
            field=django_cryptography.fields.encrypt(models.CharField(default=magicauth.utils.generate_token, max_length=255, verbose_name='Key')),
        ),
    ]
