# Generated by Django 2.2.13 on 2020-06-25 13:58

from django.db import migrations, models
import django_cryptography.fields
import magicauth.utils


class Migration(migrations.Migration):

    dependencies = [
        ('magicauth', '0005_remove_old_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magictoken',
            name='key',
            field=django_cryptography.fields.encrypt(models.CharField(default=magicauth.utils.generate_token, max_length=255, primary_key=True, serialize=False, verbose_name='Key')),
        )
    ]
